local ItemNames = {}

local ORDER = {
    "Arrow",
    "Arrow_Fire",
    "Arrow_Poison",
    "ReinforcedArrow",
    "SFArrow",
    "SkyBowArrow",
    "RoughBullet",
    "HandgunBullet",
    "RifleBullet",
    "ShotgunBullet",
    "AssaultRifleBullet",
    "GatlingBullet",
    "ExplosiveBullet",
    "GrenadeBullet",
    "MissileBullet",
    "LaserBullet",
    "LaserGatlingBullet",
    "BeamLauncherBullet",
    "ChargeLaserRifleBullet",
    "ElectricArcAssaultRifleBullet",
    "EnergyLauncherBullet",
    "EnergyShotgunBullet",
    "FlamethrowerBullet",
    "InkBullet",
    "MeteorBullet",
    "OverheatRifleBullet",
    "PalDopingShotBullet",
    "SkyAssaultRifleBullet",
    "SkyGrenadeLauncherBullet",
    "SkyShotgunBullet",
    "SkySubmachineGunBullet",
    "WidePenetrateShotgunBullet",
    "Ruby",
    "Sapphire",
    "Eemerald",
    "Diamond",
    "PalItem_ToSell_01",
    "PalItem_ToSell_02",
    "PalItem_ToSell_03",
    "PalItem_ToSell_04",
    "PalItem_ToSell_05",
    "PalSphere",
    "PalSphere_Mega",
    "PalSphere_Giga",
    "PalSphere_Tera",
    "PalSphere_Master",
    "PalSphere_Legend",
    "PalSphere_Ultimate",
    "PalSphere_Exotic",
    "PalSphere_Ancient_1",
    "PalSphere_Ancient_2",
    "FishingBait_1",
    "FishingBait_2",
    "FishingBait_3",
    "FishingBait_3_A",
}

local INDEX = {}
for index, staticId in ipairs(ORDER) do INDEX[staticId] = index end

local NAMES = {
    en = {
        "Arrow", "Fire Arrow", "Poison Arrow", "Reinforced Arrow",
        "Advanced Arrow", "Mechanical Bow Ammo", "Coarse Ammo", "Handgun Ammo",
        "Rifle Ammo", "Shotgun Shell", "Assault Rifle Ammo", "Gatling Gun Ammo",
        "Rocket Ammo", "Grenade Ammo", "Missile Ammo", "Energy Cartridge",
        "Laser Gatling Cartridge", "Beam Launcher Ammo", "Charge Rifle Ammo", "Plasma Rifle Ammo",
        "Plasma Cartridge", "Energy Shotgun Ammo", "Flamethrower Fuel", "Decal Ink",
        "Meteorite Ammo", "Overheat Rifle Ammo", "Boost Gun Ammo", "Heavy Assault Rifle Ammo",
        "Tactical Grenade Launcher Ammo", "Prototype Shotgun Ammo", "Combat SMG Ammo", "Beam Scatter Ammo",
        "Ruby", "Sapphire", "Emerald", "Diamond",
        "Precious Dragon Stone", "Precious Plume", "Precious Entrails", "Precious Claw",
        "Precious Pelt",
    },
    ["zh-hans"] = {
        "箭", "火箭", "毒箭", "强化箭矢",
        "卓越箭矢", "机械弓箭矢", "劣质弹药", "手枪子弹",
        "步枪子弹", "霰弹枪子弹", "突击步枪子弹", "加特林子弹",
        "火箭弹", "榴弹", "导弹", "能量盒",
        "加特林激光能量盒", "光束炮发射器弹药", "充能步枪子弹", "等离子步枪弹药",
        "电浆能量盒", "能量霰弹枪子弹", "火焰喷射器燃料", "印花墨水",
        "陨石弹", "过热步枪子弹", "强化枪子弹", "重型突击步枪子弹",
        "战术榴弹发射器子弹", "原型霰弹枪子弹", "战斗冲锋枪子弹", "散射光束枪弹药",
        "红宝石", "蓝宝石", "绿宝石", "钻石",
        "贵重龙珠", "贵重羽毛", "贵重内脏", "贵重爪子",
        "贵重兽毛",
    },
    ["zh-hant"] = {
        "箭矢", "火箭矢", "毒箭矢", "強化箭矢",
        "卓越箭矢", "機械弓箭矢", "劣質彈藥", "手槍子彈",
        "步槍子彈", "散彈槍子彈", "突擊步槍子彈", "加特林子彈",
        "火箭彈", "榴彈", "導彈", "能量盒",
        "加特林雷射能量盒", "光束炮發射器彈藥", "充能步槍子彈", "等離子步槍彈藥",
        "電漿能量盒", "能量散彈槍子彈", "火焰噴射器燃料", "噴漆顏料彈",
        "隕石彈", "過熱步槍子彈", "強化槍子彈", "重型突擊步槍子彈",
        "戰術榴彈發射器子彈", "原型散彈槍子彈", "戰鬥衝鋒槍子彈", "散射光束槍彈藥",
        "紅寶石", "藍寶石", "祖母綠寶石", "鑽石",
        "貴重的龍珠", "貴重的羽毛", "貴重的內臟", "貴重的利爪",
        "貴重的獸毛",
    },
    ja = {
        "矢", "火矢", "毒矢", "強化矢",
        "アドバンスアロー", "メカニカルボウの矢", "粗悪な弾薬", "ハンドガンの弾",
        "ライフルの弾", "ショットガンの弾", "アサルトライフルの弾", "ガトリング弾",
        "ロケット弾", "グレネード弾", "ミサイル弾", "エネルギーカートリッジ",
        "ガトリングレーザーカートリッジ", "ビームランチャーの弾", "チャージライフルの弾", "プラズマライフルの弾",
        "プラズマカートリッジ", "エネルギーショットガンの弾", "火炎放射器燃料", "デカールインク",
        "隕石弾", "オーバーヒートライフルの弾", "ブーストガンの弾", "ヘビーアサルトライフルの弾",
        "タクティカルグレネードランチャーの弾", "プロトタイプショットガンの弾", "コンバットサブマシンガンの弾", "ビームスキャッターの弾",
        "ルビー", "サファイア", "エメラルド", "ダイヤモンド",
        "貴重な竜玉", "貴重な羽根", "貴重な臓物", "貴重な爪",
        "貴重な獣毛",
    },
    ko = {
        "화살", "불화살", "독화살", "강화 화살",
        "발전형 화살", "정밀 기계식 활 전용 화살", "조악한 탄약", "핸드건 탄약",
        "소총 탄약", "산탄총 탄약", "돌격 소총 탄약", "개틀링탄",
        "로켓탄", "유탄", "미사일탄", "에너지 카트리지",
        "개틀링 레이저 카트리지", "빔 발사기 탄약", "충전식 소총 탄약", "플라즈마 소총 탄약",
        "플라즈마 카트리지", "에너지 산탄총 탄약", "화염방사기 연료", "데칼 잉크",
        "운석탄", "전자동 소총 탄약", "부스트 건 탄약", "중형 돌격 소총 탄약",
        "전술 유탄 발사기 탄약", "시작형 산탄총 탄약", "야전 기관단총 탄약", "빔 스캐터 탄약",
        "루비", "사파이어", "에메랄드", "다이아몬드",
        "귀중한 용옥", "귀중한 깃털", "귀중한 내장", "귀중한 발톱",
        "귀중한 동물 털",
    },
    de = {
        "Pfeil", "Feuerpfeil", "Giftpfeil", "Verstärkter Pfeil",
        "Hightech-Pfeil", "Mechanikbogen-Pfeil", "Minderwertige Munition", "Pistolenmunition",
        "Gewehrmunition", "Flintenmunition", "Sturmgewehrmunition", "Gatlinggewehrmunition",
        "Panzerfaustmunition", "Granatwerfermunition", "Raketenwerfermunition", "Energiekartusche",
        "Laser-Gatlingkartusche", "Photonenwerfermunition", "Teslagewehrmunition", "Plasmagewehrmunition",
        "Plasmakartusche", "Plasmaflintenmunition", "Flammöl", "Graffitipatrone",
        "Meteokugel", "Überhitzungsmunition", "Boostermunition", "Schwere Sturmgewehrmunition",
        "Taktische Granatwerfermunition", "Experimentelle Flintenmunition", "Gefechtsmaschinenpistolenmunition", "Photonenflintenmunition",
        "Rubin", "Saphir", "Smaragd", "Diamant",
        "Seltene Drachenkugel", "Seltene Feder", "Seltenes Organ", "Seltene Kralle",
        "Seltener Pelz",
    },
    fr = {
        "Flèche", "Flèche de feu", "Flèche empoisonnée", "Flèche renforcée",
        "Flèche avancée", "Flèches d’arc astral", "Munitions bas de gamme", "Balles de pistolet",
        "Balles de fusil", "Cartouches de fusil à pompe", "Balles de fusil d'assaut", "Munitions de gatling",
        "Munitions de roquette", "Grenade", "Missile", "Cartouche d'énergie",
        "Cartouche de gatling laser", "Munitions de canon à impulsion", "Balles de fusil chargé", "Munitions de fusil à plasma",
        "Cartouche de plasma", "Cartouches de fusil à pompe énergétique", "Combustible pour lance-flammes", "Encre pour décalco",
        "Météorites", "Balles de fusil à surchauffe", "Balles de pistolet dopant", "Cartouches de fusil d’assaut astral",
        "Munitions de lance-grenades astral", "Cartouches de fusil à pompe astral", "Balles de pistolet-mitrailleur astral", "Munitions de disperseur à faisceau",
        "Rubis", "Saphir", "Émeraude", "Diamant",
        "Orbe draconique précieux", "plume précieuse", "Entrailles précieuses", "Griffe précieuse",
        "Poils précieux",
    },
    it = {
        "Freccia", "Freccia incendiaria", "Freccia avvelenata", "Freccia potenziata",
        "Freccia avanzata", "Frecce per arco meccanico", "Proiettili mediocri", "Proiettili per pistola",
        "Proiettili per fucile", "Proiettili per fucile a canna liscia", "Proiettili per fucile d'assalto", "Proiettili per gatling",
        "Razzi", "Granate", "Razzi", "Cartuccia energetica",
        "Cartucce per gatling laser", "Colpi per arma a raggi", "Proiettili per fucile a carica", "Colpi per fucile al plasma",
        "Cartuccia al plasma", "Proiettili per fucile a canna liscia energetico", "Carburante per lanciafiamme", "Inchiostro",
        "Meteorite da lancio", "Proiettili per fucile a sovraccarico", "Proiettili per pistola potenziante", "Proiettili per fucile d'assalto pesante",
        "Proiettili per lanciagranate tattico", "Proiettili per fucile a canna liscia sperimentale", "Proiettili per mitra da guerra", "Colpi per fucile a raggi penetranti",
        "Rubino", "Zaffiro", "Smeraldo", "Diamante",
        "Globo draconico prezioso", "Piuma preziosa", "Interiora preziose", "Artiglio prezioso",
        "Vello prezioso",
    },
    es = {
        "Flecha", "Flecha incendiaria", "Flecha envenenada", "Flecha mejorada",
        "Flecha superior", "Flechas de arco mecánico", "Munición tosca", "Balas de revólver",
        "Balas de rifle", "Balas de escopeta", "Balas de rifle de asalto", "Munición de Gatling Gun",
        "Balas cohete", "Munición de granada", "Munición de misil", "Cartucho de energía",
        "Cartucho láser Gatling", "Munición de lanzarrayos", "Balas de rifle de carga", "Munición de rifle de plasma",
        "Cartucho de plasma", "Balas de escopeta de energía", "Munición de lanzallamas", "Tinta de calcomanía",
        "Bala meteorito", "Balas de rifle sobrecalentado", "Balas de pistola propulsora", "Balas de rifle de asalto pesado",
        "Munición de lanzagranadas táctico", "Balas de escopeta prototipo", "Balas de subfusil de combate", "Munición de dispersor láser",
        "Rubí", "Zafiro", "Esmeralda", "Diamante",
        "Esfera de dragón valiosa", "Pluma valiosa", "Menudillos valiosos", "Garra valiosa",
        "Pelaje valioso",
    },
    ["pt-br"] = {
        "Flecha", "Flecha de Fogo", "Flecha de Veneno", "Flecha Reforçada",
        "Flecha Avançada", "Flecha de Arco Mecânico", "Munição Inferior", "Bala de Pistola",
        "Bala de Fuzil", "Cartucho de Espingarda", "Bala de Fuzil de Assalto", "Bala de Gatling",
        "Foguete", "Granada", "Míssil", "Cartucho de Energia",
        "Cartucho de Laser para Gatling Gun", "Carga de Lança-Raios", "Bala de Fuzil de Carga", "Munição de Fuzil de Plasma",
        "Cartucho de Plasma", "Cartucho de Espingarda de Energia", "Combustível de Lança-Chamas", "Tinta de Decalque",
        "Meteorito", "Bala de Fuzil de Superaquecimento", "Bala de Arma Estimulante", "Munição de Fuzil de Assalto Pesado",
        "Carga de Lança-Granadas Tático", "Cartucho de Espingarda-Protótipo", "Munição de Submetralhadora de Combate", "Cartucho de Dispersora de Raios",
        "Rubi", "Safira", "Esmeralda", "Diamante",
        "Orbe de Dragão Valioso", "Asa Valiosa", "Víscera Valiosa", "Garra Valiosa",
        "Pele Valiosa",
    },
    ru = {
        "Стрела", "Огненная стрела", "Ядовитая стрела", "Усиленная стрела",
        "Улучшенная стрела", "Стрела механического лука", "Грубые патроны", "Патрон для пистолета",
        "Патрон для винтовки", "Патрон для дробовика", "Патрон для штурмовой винтовки", "Гатлинговые патроны",
        "Ракетный снаряд", "Гранатомётный патрон", "Ракета с наведением", "Энергетический картридж",
        "Кассета для лазерной картечницы Гатлинга", "Патрон для лучемёта", "Патрон для зарядной винтовки", "Патрон для плазменной винтовки",
        "Плазматическая кассета", "Патрон для энергетического ружья", "Топливо для огнемёта", "Чернила для граффити",
        "Метеоритный снаряд", " Патрон для перегревающейся винтовки", "Патрон для бустерной пушки", "Патрон для тяжёлой штурмовой винтовки",
        "Патрон для тактического гранатомёта", "Патрон для прототипного дробовика", "Патрон для боевого пистолет-пулемёта", "Патрон для лучерассеивателя",
        "Рубин", "Сапфир", "Изумруд", "Алмаз",
        "Ценный драконий самоцвет", "Ценное перо", "Ценные внутренности", "Ценный коготь",
        "Ценная шерсть зверя",
    },
    tr = {
        "Ok", "Ateş Oku", "Zehirli Ok", "Güçlendirilmiş Ok",
        "Gelişmiş Ok", "Mekanik Yay Oku", "Kaba Mermi", "Tabanca Mermisi",
        "Tüfek Mermisi", "Av Tüfeği Fişeği", "Taarruz Tüfeği Mermisi", "Gatling Tüfeği Mermisi",
        "Roket Mermisi", "Bomba Mermisi", "Füze Mermisi", "Enerji Kartuşu",
        "Lazer Gatling Kartuşu", "Işın Fırlatıcı Mermisi", "Şarjlı Tüfek Mermisi", "Plazma Tüfeği Mermisi",
        "Plazma Kartuşu", "Enerji Tüfeği Mermisi", "Alev Makinesi Yakıtı", "Çıkartma Mürekkebi",
        "Meteorit Mermisi", "Aşırı Isınan Tüfek Mermisi", "Takviye Tabancası Mermisi", "Ağır Taarruz Tüfeği Mermisi",
        "Taktik El Bombası Atar Mermisi", "Prototip Pompalı Tüfek Mermisi", "Hafif Makineli Tüfek Mermisi", "Işın Saçıcı Mermisi",
        "Yakut", "Safir", "Zümrüt", "Elmas",
        "Değerli Ejderha Taşı", "Değerli Kuş Tüyü", "Değerli Sakatat", "Değerli Pençe",
        "Değerli Post",
    },
    pl = {
        "Strzała", "Ognista strzała", "Zatruta strzała", "Wzmocniona strzała",
        "Zaawansowana strzała", "Strzały: Łuk mechaniczny", "Surowa amunicja", "Amunicja: Pistolet",
        "Amunicja: Karabin", "Łuska do strzelby", "Amunicja: Karabin szturmowy", "Amunicja: Kartaczownica Gatlinga",
        "Amunicja: Rakieta", "Amunicja: Granatnik", "Amunicja: Pocisk", "Nabój energetyczny",
        "Laserowy nabój do kartaczownicy Gatlinga", "Amunicja: Wyrzutnia wiązek", "Amunicja: Karabin energetyczny", "Amunicja: Karabin plazmowy",
        "Nabój plazmowy", "Amunicja: Strzelba energetyczna", "Paliwo do miotacza ognia", "Atrament do naklejek",
        "Amunicja meteorytowa", "Amunicja: Karabin przeciążeniowy", "Amunicja: Broń wzmacniająca", "Amunicja: Ciężki karabin szturmowy",
        "Amunicja: Taktyczna wyrzutnia granatów", "Amunicja: Strzelba prototypowa", "Amunicja: Bojowy pistolet maszynowy", "Amunicja: Rozszczepiacz wiązki",
        "Rubin", "Szafir", "Szmaragd", "Diament",
        "Szlachetny smoczy kamień", "Szlachetne pióro", "Szlachetne trzewia", "Szlachetny szpon",
        "Szlachetna skóra",
    },
    id = {
        "Anak Panah", "Anak Panah Api", "Anak Panah Beracun", "Anak Panah yang Ditingkatkan",
        "Anak Panah Tingkat Lanjut", "Anak Panah Busur Mekanis", "Amunisi Kasar", "Peluru Pistol Tangan",
        "Peluru Senapan", "Peluru Shotgun", "Peluru Senapan Serbu", "Peluru Gatling",
        "Bom Roket", "Peluru Granat", "Peluru Rudal", "Kartrij Energi",
        "Kartrij Gatling Laser", "Amunisi Peluncur Sinar", "Peluru Senapan Charge", "Amunisi Senapan Plasma",
        "Kartrij Plasma", "Peluru Energy Shotgun", "Peluru Penyembur Api", "Tinta Stiker",
        "Peluru Meteorit", "Peluru Senapan Overheat", "Peluru Burstgun", "Amunisi Senapan Serbu Berat",
        "Amunisi Pelontar Granat Taktis", "Amunisi Shotgun Prototipe", "Amunisi Senapan Mesin Ringan Tempur", "Amunisi Sinar Menyebar",
        "Rubi", "Safir", "Zamrud", "Berlian",
        "Sphere Naga Berharga", "Bulu Berharga", "Jeroan Berharga", "Kuku Berharga",
        "Bulu Binatang Berharga",
    },
    ["es-419"] = {
        "Flecha", "Flecha ígnea", "Flecha envenenada", "Flecha mejorada",
        "Flecha superior", "Flechas de arco mecánico", "Munición de baja calidad", "Balas para pistola",
        "Balas de rifle", "Balas de escopeta", "Balas de rifle de asalto", "Munición de ametralladora Gatling",
        "Balas de cohete", "Munición de granada", "Munición de misil", "Cartucho de energía",
        "Cartucho de láser Gatling", "Munición de lanzador de rayos", "Munición para cañón de carga", "Munición de rifle de plasma",
        "Cartucho de plasma", "Munición para escopeta de energía", "Combustible de lanzallamas", "Tinta de calcomanía",
        "Munición de meteorito", "Balas para rifle de sobrecalentamiento", "Balas de pistola propulsora", "Munición de rifle de asalto pesado",
        "Munición de lanzagranadas táctico", "Munición de escopeta prototipo", "Munición de subfusil de combate", "Munición de dispersor de rayos",
        "Rubí", "Zafiro", "Esmeralda", "Diamante",
        "Gema de dragón valiosa", "Pluma valiosa", "Vísceras valiosas", "Garra valiosa",
        "Pelaje valioso",
    },
    th = {
        "ลูกศร", "ลูกศรไฟ", "ลูกศรพิษ", "ลูกศรเสริมแรง",
        "ลูกศรเหนือระดับ", "ลูกธนูกลไก", "กระสุนคุณภาพต่ำ", "กระสุนปืนพก",
        "กระสุนไรเฟิล", "กระสุนปืนลูกซอง", "กระสุนปืนไรเฟิลจู่โจม", "กระสุนปืนแก็ตลิง",
        "กระสุนจรวด", "กระสุนระเบิด", "กระสุนมิสไซล์", "ตลับพลังงาน",
        "ตลับพลังงานปืนเลเซอร์แก็ตลิง", "ลูกกระสุนปืนตัวปล่อยแสง", "กระสุนชาร์จไรเฟิล", "ลูกกระสุนปืนไรเฟิลพลาสมา",
        "ตลับพลังงานพลาสมา", "กระสุนปืนลูกซองพลังงาน", "เชื้อเพลิงเครื่องพ่นไฟ", "หมึกปืนวาดภาพ",
        "กระสุนอุกกาบาต", "กระสุนโอเวอร์ฮีตไรเฟิล", "กระสุนบูสต์กัน", "ลูกกระสุนปืนไรเฟิลจู่โจม",
        "ลูกกระสุนเครื่องยิงระเบิดเชิงยุทธวิธี", "ลูกกระสุนปืนลูกซองรุ่นต้นแบบ", "ลูกกระสุนปืนกลมือสำหรับการต่อสู้", "ลูกกระสุนปืนของลำแสงกระจาย",
        "ทับทิม", "ไพลิน", "มรกต", "เพชร",
        "มุกมังกรล้ำค่า", "ขนนกล้ำค่า", "เครื่องในล้ำค่า", "เล็บล้ำค่า",
        "ขนสัตว์ล้ำค่า",
    },
    vi = {
        "Mũi Tên", "Mũi Tên Lửa", "Mũi Tên Độc", "Mũi Tên Cường Hóa",
        "Mũi Tên Nâng Cấp", "Mũi Tên Cung Cơ Khí", "Đạn Thô", "Đạn Súng Ngắn",
        "Đạn Súng Trường", "Đạn Súng Săn", "Đạn Súng Trường Tấn Công", "Đạn Súng Nòng Xoay",
        "Tên Lửa", "Lựu Đạn", "Tên Lửa Điều Khiển", "Đạn Năng Lượng",
        "Đạn Súng Nòng Xoay Laser", "Đạn Thiết Bị Phóng Chùm Tia", "Đạn Súng Trường Năng Lượng", "Đạn Súng Trường Plasma",
        "Đạn Plasma", "Đạn Súng Săn Năng Lượng", "Nhiên Liệu Súng Phun Lửa", "Đạn Súng Bắn Decal",
        "Đạn Thiên Thạch", "Đạn Súng Trường Quá Nhiệt", "Đạn Súng Cường Lực", "Đạn Súng Trường Tấn Công Hạng Nặng",
        "Đạn Súng Phóng Lựu Chiến Thuật", "Đạn Súng Săn Nguyên Mẫu", "Đạn Súng Tiểu Liên Chiến Đấu", "Đạn Súng Năng Lượng Tán Xạ",
        "Hồng Ngọc", "Đá Sapphire", "Ngọc Lục Bảo", "Kim Cương",
        "Ngọc Rồng Quý Giá", "Lông Vũ Quý Giá", "Nội Tạng Quý Giá", "Móng Vuốt Quý Giá",
        "Bộ Lông Quý Giá",
    },
}

local EXTRA_NAMES = {
    en = { "Pal Sphere", "Mega Sphere", "Giga Sphere", "Hyper Sphere", "Ultra Sphere", "Legendary Sphere", "Ultimate Sphere", "Exotic Sphere", "Sol Sphere", "Ancient Sphere", "Simple Bait", "High Quality Bait", "Deluxe Bait", "Alluring Bait" },
    ["zh-hans"] = { "帕鲁球", "高级帕鲁球", "优质帕鲁球", "特级帕鲁球", "大师帕鲁球", "传奇帕鲁球", "究极帕鲁球", "超限帕鲁球", "烈阳帕鲁球", "远古帕鲁球", "简陋钓饵", "优质钓饵", "奢华钓饵", "魅惑钓饵" },
    ["zh-hant"] = { "帕魯球", "高級帕魯球", "優質帕魯球", "特級帕魯球", "大師帕魯球", "傳奇帕魯球", "究極帕魯球", "超限帕魯球", "烈陽帕魯球", "遠古帕魯球", "簡陋釣餌", "優質釣餌", "奢華釣餌", "魅惑釣餌" },
    ja = { "パルスフィア", "メガスフィア", "ギガスフィア", "テラスフィア", "ウルトラスフィア", "レジェンドスフィア", "アルティメットスフィア", "インフィニティスフィア", "ソルスフィア", "エンシェントスフィア", "質素な釣りエサ", "上質な釣りエサ", "贅沢な釣りエサ", "魅惑の釣りエサ" },
    ko = { "팰 스피어", "메가 스피어", "기가 스피어", "테라 스피어", "울트라 스피어", "전설 스피어", "얼티밋 스피어", "인피니티 스피어", "솔 스피어", "고대 스피어", "소박한 낚시 미끼", "질 좋은 낚시 미끼", "호화로운 낚시 미끼", "매혹적인 낚시 미끼" },
    de = { "Pal-Sphäre", "Mega-Sphäre", "Giga-Sphäre", "Tera-Sphäre", "Ultra-Sphäre", "Legendäre Sphäre", "Ultimative Sphäre", "Exotische Sphäre", "Soralitsphäre", "Antike Sphäre", "Einfacher Köder", "Hochwertiger Köder", "Luxus-Köder", "Betörender Köder" },
    fr = { "Sphère de Pal", "Méga Sphère", "Giga Sphère", "Hyper Sphère", "Ultra Sphère", "Sphère Légendaire", "Sphère Ultime", "Sphère Exotique", "Sphère Astrale", "Sphère Antique", "Appât modeste", "Appât haut de gamme", "Appât de luxe", "Appât séduisant" },
    it = { "Sfera Pal", "Sfera mega", "Sfera giga", "Sfera tera", "Sfera ultra", "Sfera leggendaria", "Sfera definitiva", "Sfera dell'infinito", "Sfera di Soralite", "Sfera antica", "Esca base", "Esca di qualità", "Esca di prima scelta", "Esca seducente" },
    es = { "Esfera Pal", "Megaesfera", "Gigaesfera", "Teraesfera", "Ultraesfera", "Mitoesfera", "Esfera definitiva", "Esfera infinita", "Solesfera", "Esfera ancestral", "Cebo de pesca humilde", "Cebo de pesca de calidad", "Cebo de pesca lujoso", "Cebo de pesca encantador" },
    ["pt-br"] = { "Esfera de Pal", "Esfera Mega", "Esfera Giga", "Esfera Tera", "Esfera Ultra", "Esfera Lendária", "Esfera Suprema", "Esfera da Infinidade", "Esfera Soralítica", "Esfera Antiga", "Isca Simples", "Isca Requintada", "Isca Extravagante", "Isca Sedutora" },
    ru = { "Пал-сфера", "Мегасфера", "Гигасфера", "Терасфера", "Ультрасфера", "Легендарная сфера", "Абсолютная сфера", "Сфера инфинити", "Соллайт сфера", "Древняя сфера", "Простая приманка", "Качественная приманка", "Роскошная приманка", "Заманчивая приманка" },
    tr = { "Pal Küresi", "Mega Küre", "Giga Küre", "Hiper Küre", "Ultra Küre", "Efsanevi Küre", "Nihai Küre", "Egzotik Küre", "Sol-Küre", "Kadim Küre", "Sade Balık Yemi", "Kaliteli Balık Yemi", "Lüks Balık Yemi", "Çekici Balık Yemi" },
    pl = { "Pal Sfera", "Mega Sfera", "Giga Sfera", "Hiper Sfera", "Ultra Sfera", "Legendarna Sfera", "Ostateczna Sfera", "Egzotyczna Sfera", "Solsfera", "Starożytna Sfera", "Prosta przynęta wędkarska", "Wysokiej jakości przynęta wędkarska", "Luksusowa przynęta wędkarska", "Kusząca przynęta wędkarska" },
    id = { "Pal Sphere", "Mega Sphere", "Giga Sphere", "Hyper Sphere", "Ultra Sphere", "Legendary Sphere", "Pal Sphere Terbaik", "Exotic Sphere", "Sphere Sol", "Sphere Kuno", "Umpan Pancing Sederhana", "Umpan Pancing Berkualitas Tinggi", "Umpan Pancing Mewah", "Umpan Pancing Pemikat" },
    ["es-419"] = { "Palesfera", "Megaesfera", "Gigaesfera", "Teraesfera", "Ultraesfera", "Mitoesfera", "Esfera definitiva", "Infinitoesfera", "Esfera de Sol", "Esfera antigua", "Cebo de pesca simple", "Cebo de pesca de alta calidad", "Cebo de pesca lujoso", "Cebo de pesca encantador" },
    th = { "พาลสเฟียร์", "เมกาสเฟียร์", "กิกาสเฟียร์", "เทราสเฟียร์", "อัลตราสเฟียร์", "เลเจนด์สเฟียร์", "อัลติเมตสเฟียร์", "อินฟินิตี้สเฟียร์", "โซลสเฟียร์", "สเฟียร์โบราณ", "เหยื่อตกปลาธรรมดา", "เหยื่อตกปลาคุณภาพดี", "เหยื่อตกปลาคุณภาพสูง", "เหยื่อตกปลาเสน่หหา" },
    vi = { "Quả Cầu Pal", "Quả Cầu Mega", "Quả Cầu Giga", "Quả Cầu Hyper", "Quả Cầu Ultra", "Quả Cầu Legendary", "Quả Cầu Ultimate", "Quả Cầu Exotic", "Quả Cầu Soralite", "Quả Cầu Pal Cổ Đại", "Mồi Câu Đơn Giản", "Mồi Câu Cao Cấp", "Mồi Câu Xa Xỉ", "Mồi Câu Mê Hoặc" },
}

for locale, names in pairs(EXTRA_NAMES) do
    local target = NAMES[locale]
    for _, name in ipairs(names) do target[#target + 1] = name end
end

function ItemNames.get(locale, staticId)
    local index = INDEX[tostring(staticId or "")]
    if index == nil then return nil end
    local names = NAMES[tostring(locale or "")] or NAMES.en
    return names[index] or NAMES.en[index]
end

return ItemNames
