local P = require("palworld")

local Localization = {}

local SUPPORTED_LOCALES = {
    "en", "zh-hans", "zh-hant", "ja", "ko", "de", "fr", "it", "es",
    "pt-br", "ru", "tr", "pl", "id", "es-419", "th", "vi",
}

local SUPPORTED_LOCALE_SET = {}
for _, locale in ipairs(SUPPORTED_LOCALES) do
    SUPPORTED_LOCALE_SET[locale] = true
end

local STRINGS = {
    en = {
        overflow = "%d more item types not shown",
        countdown = "Closes automatically in %d s",
        confirm = "OK",
        fullSection = "Not stored · Storage full",
        fullSummary = "%d types · %d items remain",
        fullHelper = "Storage is full. These items remain in your inventory.",
        movedSection = "Stored",
        countSummary = "%d types · %d items",
        excludedSection = "Excluded",
        partialTitle = "Some items were not stored",
        failedTitle = "Items were not stored",
        submittedTitle = "Storage request sent",
        completeTitle = "Quick Stack complete",
        started = "Storing items… Please do not perform other actions",
        submittedCompact = "Storage request sent. Check again shortly",
        partialCompact = "Stored %d items · %d not stored",
        completeCompact = "Stored %d items",
        fullCompact = "Storage full · %d items not stored",
        completeContainers = "Stored %d items in %d containers",
        noop = "No items can be stored",
        stopped = "Quick Stack stopped",
    },
    ["zh-hans"] = {
        overflow = "另有 %d 种物品未展开",
        countdown = "将在 %d 秒后自动关闭",
        confirm = "确定",
        fullSection = "未能收纳 · 存储空间已满",
        fullSummary = "%d 种 · %d 件仍在背包",
        fullHelper = "存储空间已满，这些物品仍留在背包中。",
        movedSection = "已收纳",
        countSummary = "%d 种 · %d 件",
        excludedSection = "已排除",
        partialTitle = "部分物品未能收纳",
        failedTitle = "未能收纳",
        submittedTitle = "收纳请求已发送",
        completeTitle = "收纳完成",
        started = "收纳中……请勿进行其他操作",
        submittedCompact = "收纳请求已发送，请稍后查看",
        partialCompact = "收纳完成：%d 件；%d 件未收纳",
        completeCompact = "收纳完成：%d 件物品",
        fullCompact = "存储空间已满：%d 件未能收纳",
        completeContainers = "收纳完成：%d 件物品，%d 个容器",
        noop = "没有可收纳的物品",
        stopped = "收纳已停止",
    },
    ["zh-hant"] = {
        overflow = "另有 %d 種物品未展開",
        countdown = "將在 %d 秒後自動關閉",
        confirm = "確定",
        fullSection = "未能收納 · 儲存空間已滿",
        fullSummary = "%d 種 · %d 件仍在背包",
        fullHelper = "儲存空間已滿，這些物品仍留在背包中。",
        movedSection = "已收納",
        countSummary = "%d 種 · %d 件",
        excludedSection = "已排除",
        partialTitle = "部分物品未能收納",
        failedTitle = "未能收納",
        submittedTitle = "收納請求已傳送",
        completeTitle = "收納完成",
        started = "收納中……請勿進行其他操作",
        submittedCompact = "收納請求已傳送，請稍後查看",
        partialCompact = "收納完成：%d 件；%d 件未收納",
        completeCompact = "收納完成：%d 件物品",
        fullCompact = "儲存空間已滿：%d 件未能收納",
        completeContainers = "收納完成：%d 件物品，%d 個容器",
        noop = "沒有可收納的物品",
        stopped = "收納已停止",
    },
    ja = {
        overflow = "ほか %d 種類は省略",
        countdown = "%d 秒後に自動で閉じます",
        confirm = "決定",
        fullSection = "収納できません · 空き容量なし",
        fullSummary = "%d 種類 · %d 個がバッグに残っています",
        fullHelper = "収納先が満杯のため、これらのアイテムはバッグに残っています。",
        movedSection = "収納済み",
        countSummary = "%d 種類 · %d 個",
        excludedSection = "除外",
        partialTitle = "一部のアイテムを収納できませんでした",
        failedTitle = "アイテムを収納できませんでした",
        submittedTitle = "収納リクエストを送信しました",
        completeTitle = "収納完了",
        started = "収納中…ほかの操作をしないでください",
        submittedCompact = "収納リクエスト送信済み。後で確認してください",
        partialCompact = "%d 個を収納 · %d 個は未収納",
        completeCompact = "%d 個のアイテムを収納しました",
        fullCompact = "収納先が満杯 · %d 個を収納できません",
        completeContainers = "%d 個を %d 個の収納先に収納しました",
        noop = "収納できるアイテムがありません",
        stopped = "収納を停止しました",
    },
    ko = {
        overflow = "그 외 %d종은 표시하지 않음",
        countdown = "%d초 후 자동으로 닫힙니다",
        confirm = "확인",
        fullSection = "보관 실패 · 보관함 가득 참",
        fullSummary = "%d종 · %d개가 가방에 남음",
        fullHelper = "보관 공간이 가득 차 이 아이템은 가방에 남아 있습니다.",
        movedSection = "보관 완료",
        countSummary = "%d종 · %d개",
        excludedSection = "제외됨",
        partialTitle = "일부 아이템을 보관하지 못했습니다",
        failedTitle = "아이템을 보관하지 못했습니다",
        submittedTitle = "보관 요청을 보냈습니다",
        completeTitle = "빠른 보관 완료",
        started = "보관 중… 다른 작업을 하지 마세요",
        submittedCompact = "보관 요청을 보냈습니다. 잠시 후 확인하세요",
        partialCompact = "%d개 보관 · %d개 보관 실패",
        completeCompact = "%d개 아이템 보관 완료",
        fullCompact = "보관함 가득 참 · %d개 보관 실패",
        completeContainers = "%d개 아이템을 %d개 보관함에 보관",
        noop = "보관할 수 있는 아이템이 없습니다",
        stopped = "빠른 보관을 중지했습니다",
    },
    de = {
        overflow = "%d weitere Gegenstandsarten ausgeblendet",
        countdown = "Schließt automatisch in %d s",
        confirm = "OK",
        fullSection = "Nicht verstaut · Lager voll",
        fullSummary = "%d Arten · %d Gegenstände im Inventar",
        fullHelper = "Der Lagerplatz ist voll. Diese Gegenstände bleiben im Inventar.",
        movedSection = "Verstaut",
        countSummary = "%d Arten · %d Gegenstände",
        excludedSection = "Ausgeschlossen",
        partialTitle = "Einige Gegenstände wurden nicht verstaut",
        failedTitle = "Gegenstände wurden nicht verstaut",
        submittedTitle = "Lageranfrage gesendet",
        completeTitle = "Schnellverstauen abgeschlossen",
        started = "Verstauen läuft… Bitte nichts anderes tun",
        submittedCompact = "Lageranfrage gesendet. Bitte kurz warten",
        partialCompact = "%d verstaut · %d nicht verstaut",
        completeCompact = "%d Gegenstände verstaut",
        fullCompact = "Lager voll · %d nicht verstaut",
        completeContainers = "%d Gegenstände in %d Behältern verstaut",
        noop = "Keine passenden Gegenstände",
        stopped = "Schnellverstauen gestoppt",
    },
    fr = {
        overflow = "Encore %d types d’objets masqués",
        countdown = "Fermeture automatique dans %d s",
        confirm = "OK",
        fullSection = "Non rangé · Stockage plein",
        fullSummary = "%d types · %d objets dans l’inventaire",
        fullHelper = "Le stockage est plein. Ces objets restent dans l’inventaire.",
        movedSection = "Rangé",
        countSummary = "%d types · %d objets",
        excludedSection = "Exclus",
        partialTitle = "Certains objets n’ont pas été rangés",
        failedTitle = "Objets non rangés",
        submittedTitle = "Demande de rangement envoyée",
        completeTitle = "Rangement terminé",
        started = "Rangement en cours… N’effectuez aucune autre action",
        submittedCompact = "Demande envoyée. Vérifiez dans un instant",
        partialCompact = "%d objets rangés · %d non rangés",
        completeCompact = "%d objets rangés",
        fullCompact = "Stockage plein · %d objets non rangés",
        completeContainers = "%d objets rangés dans %d conteneurs",
        noop = "Aucun objet à ranger",
        stopped = "Rangement arrêté",
    },
    it = {
        overflow = "Altri %d tipi di oggetti non mostrati",
        countdown = "Chiusura automatica tra %d s",
        confirm = "OK",
        fullSection = "Non depositati · Spazio esaurito",
        fullSummary = "%d tipi · %d oggetti nell’inventario",
        fullHelper = "Lo spazio è esaurito. Questi oggetti restano nell’inventario.",
        movedSection = "Depositati",
        countSummary = "%d tipi · %d oggetti",
        excludedSection = "Esclusi",
        partialTitle = "Alcuni oggetti non sono stati depositati",
        failedTitle = "Oggetti non depositati",
        submittedTitle = "Richiesta di deposito inviata",
        completeTitle = "Deposito rapido completato",
        started = "Deposito in corso… Non eseguire altre azioni",
        submittedCompact = "Richiesta inviata. Controlla tra poco",
        partialCompact = "%d depositati · %d non depositati",
        completeCompact = "%d oggetti depositati",
        fullCompact = "Spazio esaurito · %d non depositati",
        completeContainers = "%d oggetti depositati in %d contenitori",
        noop = "Nessun oggetto da depositare",
        stopped = "Deposito rapido interrotto",
    },
    es = {
        overflow = "Otros %d tipos de objetos no se muestran",
        countdown = "Se cerrará automáticamente en %d s",
        confirm = "OK",
        fullSection = "Sin guardar · Almacenamiento lleno",
        fullSummary = "%d tipos · %d objetos en el inventario",
        fullHelper = "El almacenamiento está lleno. Estos objetos siguen en el inventario.",
        movedSection = "Guardados",
        countSummary = "%d tipos · %d objetos",
        excludedSection = "Excluidos",
        partialTitle = "Algunos objetos no se pudieron guardar",
        failedTitle = "No se pudieron guardar los objetos",
        submittedTitle = "Solicitud de almacenamiento enviada",
        completeTitle = "Guardado rápido completado",
        started = "Guardando objetos… No realices otras acciones",
        submittedCompact = "Solicitud enviada. Compruébalo en unos instantes",
        partialCompact = "%d guardados · %d sin guardar",
        completeCompact = "%d objetos guardados",
        fullCompact = "Almacenamiento lleno · %d sin guardar",
        completeContainers = "%d objetos guardados en %d contenedores",
        noop = "No hay objetos que se puedan guardar",
        stopped = "Guardado rápido detenido",
    },
    ["pt-br"] = {
        overflow = "Outros %d tipos de itens não exibidos",
        countdown = "Fechará automaticamente em %d s",
        confirm = "OK",
        fullSection = "Não armazenado · Armazenamento cheio",
        fullSummary = "%d tipos · %d itens no inventário",
        fullHelper = "O armazenamento está cheio. Estes itens continuam no inventário.",
        movedSection = "Armazenado",
        countSummary = "%d tipos · %d itens",
        excludedSection = "Excluído",
        partialTitle = "Alguns itens não foram armazenados",
        failedTitle = "Itens não armazenados",
        submittedTitle = "Solicitação de armazenamento enviada",
        completeTitle = "Armazenamento rápido concluído",
        started = "Armazenando itens… Não realize outras ações",
        submittedCompact = "Solicitação enviada. Verifique em instantes",
        partialCompact = "%d armazenados · %d não armazenados",
        completeCompact = "%d itens armazenados",
        fullCompact = "Armazenamento cheio · %d não armazenados",
        completeContainers = "%d itens armazenados em %d contêineres",
        noop = "Nenhum item pode ser armazenado",
        stopped = "Armazenamento rápido interrompido",
    },
    ru = {
        overflow = "Ещё %d типов предметов не показано",
        countdown = "Автозакрытие через %d с",
        confirm = "ОК",
        fullSection = "Не перемещено · Хранилище заполнено",
        fullSummary = "%d типов · %d предметов в инвентаре",
        fullHelper = "Хранилище заполнено. Эти предметы остались в инвентаре.",
        movedSection = "Перемещено",
        countSummary = "%d типов · %d предметов",
        excludedSection = "Исключено",
        partialTitle = "Часть предметов не перемещена",
        failedTitle = "Предметы не перемещены",
        submittedTitle = "Запрос на перемещение отправлен",
        completeTitle = "Быстрое перемещение завершено",
        started = "Перемещение… Не выполняйте другие действия",
        submittedCompact = "Запрос отправлен. Проверьте позже",
        partialCompact = "%d перемещено · %d не перемещено",
        completeCompact = "%d предметов перемещено",
        fullCompact = "Хранилище заполнено · %d не перемещено",
        completeContainers = "%d предметов перемещено в %d контейнеров",
        noop = "Нет предметов для перемещения",
        stopped = "Быстрое перемещение остановлено",
    },
    tr = {
        overflow = "%d öğe türü daha gösterilmiyor",
        countdown = "%d sn sonra otomatik kapanacak",
        confirm = "Tamam",
        fullSection = "Depolanamadı · Depo dolu",
        fullSummary = "%d tür · %d öğe envanterde",
        fullHelper = "Depo dolu. Bu öğeler envanterde kaldı.",
        movedSection = "Depolandı",
        countSummary = "%d tür · %d öğe",
        excludedSection = "Hariç tutuldu",
        partialTitle = "Bazı öğeler depolanamadı",
        failedTitle = "Öğeler depolanamadı",
        submittedTitle = "Depolama isteği gönderildi",
        completeTitle = "Hızlı depolama tamamlandı",
        started = "Öğeler depolanıyor… Başka işlem yapmayın",
        submittedCompact = "Depolama isteği gönderildi. Birazdan kontrol edin",
        partialCompact = "%d depolandı · %d depolanamadı",
        completeCompact = "%d öğe depolandı",
        fullCompact = "Depo dolu · %d öğe depolanamadı",
        completeContainers = "%d öğe %d konteynere depolandı",
        noop = "Depolanabilecek öğe yok",
        stopped = "Hızlı depolama durduruldu",
    },
    pl = {
        overflow = "Nie pokazano jeszcze %d typów przedmiotów",
        countdown = "Automatyczne zamknięcie za %d s",
        confirm = "OK",
        fullSection = "Nie przeniesiono · Magazyn pełny",
        fullSummary = "%d typów · %d przedmiotów w ekwipunku",
        fullHelper = "Magazyn jest pełny. Te przedmioty pozostają w ekwipunku.",
        movedSection = "Przeniesiono",
        countSummary = "%d typów · %d przedmiotów",
        excludedSection = "Wykluczono",
        partialTitle = "Nie przeniesiono części przedmiotów",
        failedTitle = "Nie przeniesiono przedmiotów",
        submittedTitle = "Wysłano żądanie przeniesienia",
        completeTitle = "Szybkie przenoszenie zakończone",
        started = "Przenoszenie… Nie wykonuj innych czynności",
        submittedCompact = "Wysłano żądanie. Sprawdź za chwilę",
        partialCompact = "%d przeniesiono · %d nie przeniesiono",
        completeCompact = "%d przedmiotów przeniesiono",
        fullCompact = "Magazyn pełny · %d nie przeniesiono",
        completeContainers = "%d przedmiotów przeniesiono do %d pojemników",
        noop = "Brak przedmiotów do przeniesienia",
        stopped = "Szybkie przenoszenie zatrzymane",
    },
    id = {
        overflow = "%d jenis item lainnya tidak ditampilkan",
        countdown = "Tutup otomatis dalam %d dtk",
        confirm = "OK",
        fullSection = "Tidak tersimpan · Penyimpanan penuh",
        fullSummary = "%d jenis · %d item tetap di inventaris",
        fullHelper = "Penyimpanan penuh. Item ini tetap berada di inventaris.",
        movedSection = "Tersimpan",
        countSummary = "%d jenis · %d item",
        excludedSection = "Dikecualikan",
        partialTitle = "Sebagian item tidak dapat disimpan",
        failedTitle = "Item tidak dapat disimpan",
        submittedTitle = "Permintaan penyimpanan dikirim",
        completeTitle = "Penyimpanan cepat selesai",
        started = "Menyimpan item… Jangan lakukan tindakan lain",
        submittedCompact = "Permintaan dikirim. Periksa sebentar lagi",
        partialCompact = "%d tersimpan · %d tidak tersimpan",
        completeCompact = "%d item tersimpan",
        fullCompact = "Penyimpanan penuh · %d item tidak tersimpan",
        completeContainers = "%d item tersimpan di %d wadah",
        noop = "Tidak ada item yang dapat disimpan",
        stopped = "Penyimpanan cepat dihentikan",
    },
    ["es-419"] = {
        overflow = "Otros %d tipos de objetos no se muestran",
        countdown = "Se cerrará automáticamente en %d s",
        confirm = "OK",
        fullSection = "Sin guardar · Almacenamiento lleno",
        fullSummary = "%d tipos · %d objetos en el inventario",
        fullHelper = "El almacenamiento está lleno. Estos objetos siguen en el inventario.",
        movedSection = "Guardados",
        countSummary = "%d tipos · %d objetos",
        excludedSection = "Excluidos",
        partialTitle = "Algunos objetos no se pudieron guardar",
        failedTitle = "No se pudieron guardar los objetos",
        submittedTitle = "Solicitud de almacenamiento enviada",
        completeTitle = "Guardado rápido completado",
        started = "Guardando objetos… No hagas otras acciones",
        submittedCompact = "Solicitud enviada. Revisa en un momento",
        partialCompact = "%d guardados · %d sin guardar",
        completeCompact = "%d objetos guardados",
        fullCompact = "Almacenamiento lleno · %d sin guardar",
        completeContainers = "%d objetos guardados en %d contenedores",
        noop = "No hay objetos que se puedan guardar",
        stopped = "Guardado rápido detenido",
    },
    th = {
        overflow = "มีอีก %d ประเภทที่ไม่ได้แสดง",
        countdown = "จะปิดอัตโนมัติใน %d วินาที",
        confirm = "ตกลง",
        fullSection = "จัดเก็บไม่ได้ · ที่เก็บเต็ม",
        fullSummary = "%d ประเภท · %d ชิ้นยังอยู่ในกระเป๋า",
        fullHelper = "ที่เก็บเต็ม ไอเทมเหล่านี้ยังอยู่ในกระเป๋า",
        movedSection = "จัดเก็บแล้ว",
        countSummary = "%d ประเภท · %d ชิ้น",
        excludedSection = "ยกเว้นแล้ว",
        partialTitle = "บางไอเทมไม่สามารถจัดเก็บได้",
        failedTitle = "ไม่สามารถจัดเก็บไอเทมได้",
        submittedTitle = "ส่งคำขอจัดเก็บแล้ว",
        completeTitle = "จัดเก็บด่วนเสร็จสิ้น",
        started = "กำลังจัดเก็บ… โปรดอย่าดำเนินการอื่น",
        submittedCompact = "ส่งคำขอแล้ว โปรดตรวจสอบภายหลัง",
        partialCompact = "จัดเก็บแล้ว %d ชิ้น · ไม่ได้จัดเก็บ %d ชิ้น",
        completeCompact = "จัดเก็บแล้ว %d ชิ้น",
        fullCompact = "ที่เก็บเต็ม · ไม่ได้จัดเก็บ %d ชิ้น",
        completeContainers = "จัดเก็บ %d ชิ้นใน %d กล่อง",
        noop = "ไม่มีไอเทมที่จัดเก็บได้",
        stopped = "หยุดการจัดเก็บด่วนแล้ว",
    },
    vi = {
        overflow = "Còn %d loại vật phẩm không hiển thị",
        countdown = "Tự động đóng sau %d giây",
        confirm = "OK",
        fullSection = "Chưa cất · Kho đã đầy",
        fullSummary = "%d loại · %d vật phẩm còn trong túi",
        fullHelper = "Kho đã đầy. Các vật phẩm này vẫn ở trong túi.",
        movedSection = "Đã cất",
        countSummary = "%d loại · %d vật phẩm",
        excludedSection = "Đã loại trừ",
        partialTitle = "Một số vật phẩm chưa được cất",
        failedTitle = "Không thể cất vật phẩm",
        submittedTitle = "Đã gửi yêu cầu cất đồ",
        completeTitle = "Cất nhanh hoàn tất",
        started = "Đang cất đồ… Không thực hiện thao tác khác",
        submittedCompact = "Đã gửi yêu cầu. Hãy kiểm tra lại sau",
        partialCompact = "%d đã cất · %d chưa cất",
        completeCompact = "%d vật phẩm đã cất",
        fullCompact = "Kho đã đầy · %d vật phẩm chưa cất",
        completeContainers = "Đã cất %d vật phẩm vào %d kho",
        noop = "Không có vật phẩm có thể cất",
        stopped = "Đã dừng cất nhanh",
    },
}

local function stringValue(value)
    if type(value) == "string" then return value end
    local result
    if value ~= nil then
        pcall(function() result = value:ToString() end)
    end
    return type(result) == "string" and result or nil
end

local function languageTag()
    local i18n = P.staticObject(
        "/Script/Engine.Default__KismetInternationalizationLibrary")
    if not P.isValid(i18n) then return "en" end
    local value
    pcall(function() value = i18n:GetCurrentLanguage() end)
    local tag = stringValue(value)
    if tag == nil or tag == "" then
        pcall(function() value = i18n:GetCurrentCulture() end)
        tag = stringValue(value)
    end
    return string.lower(tag or "en")
end

local function localeKeyFromTag(tag)
    tag = string.lower(tostring(tag or "en"))
    if tag:find("zh%-hant", 1, false) or tag:find("zh%-tw", 1, false)
        or tag:find("zh%-hk", 1, false) then
        return "zh-hant"
    end
    if tag:find("zh", 1, true) then return "zh-hans" end
    if tag:find("pt", 1, true) then return "pt-br" end
    if tag:find("es%-419", 1, false) or tag:find("es%-mx", 1, false)
        or tag:find("es%-ar", 1, false) or tag:find("latam", 1, true) then
        return "es-419"
    end
    local short = tag:match("^[a-z]+") or "en"
    return SUPPORTED_LOCALE_SET[short] and short or "en"
end

function Localization.current()
    return STRINGS[localeKeyFromTag(languageTag())] or STRINGS.en
end

function Localization.format(strings, key, ...)
    local row = type(strings) == "table" and strings or STRINGS.en
    local template = row[key] or STRINGS.en[key]
    if type(template) ~= "string" then return tostring(key) end
    local ok, value = pcall(string.format, template, ...)
    return ok and value or template
end

return Localization
